# Generated by Django 5.1 on 2024-08-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
