# Generated by Django 5.1 on 2024-08-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_postagem_categoria_alter_postagem_imagens_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postagem',
            old_name='data',
            new_name='criado',
        ),
    ]
