# Generated by Django 5.1 on 2024-08-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_data_postagem_criado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='data',
            new_name='criada_em',
        ),
        migrations.RenameField(
            model_name='postagem',
            old_name='criado',
            new_name='criada_em',
        ),
    ]
