# Generated by Django 5.1 on 2024-08-10 13:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_atualizacao_categoria_atualizada_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='descricao',
        ),
        migrations.AddField(
            model_name='postagem',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
