# Generated by Django 5.1 on 2024-08-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_postagem_descricao_postagem_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
