# Generated by Django 5.1 on 2024-08-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_comentarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ['id'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
    ]
