# Generated by Django 5.1 on 2024-08-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_comentarios_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
